export * from "./facebook";
export * from "./appIcon";
export * from "./menuIcon";
export * from "./intagram";
export * from "./whatsapp";
export * from "./linkedIn";
export * from "./twitter";
export * from "./mail";
export * from './tel'